import { useState, useEffect } from 'react';
import { db } from './utils/db';
import type { DbState, Booking, Transaction, BookingStatus, Service, Barber, Admin } from './types';
import { LandingPage } from './components/LandingPage';
import { AdminLogin } from './components/AdminLogin';
import { AdminDashboard } from './components/AdminDashboard';
import { useToast, ToastContainer } from './components/ui/CustomComponents';
import { verifyJwt } from './utils/jwt';

// Safe storage wrappers to prevent Safari Private Mode from throwing SecurityErrors
const getStorageItem = (key: string): string | null => {
  try {
    return sessionStorage.getItem(key) || localStorage.getItem(key);
  } catch (e) {
    return null;
  }
};

const removeStorageItem = (key: string): void => {
  try {
    sessionStorage.removeItem(key);
    localStorage.removeItem(key);
  } catch (e) {}
};

function App() {
  const [view, setView] = useState<'landing' | 'login' | 'dashboard'>('landing');
  const [isAdminAuthenticated, setIsAdminAuthenticated] = useState<boolean>(() => {
    return !!getStorageItem('admin_token');
  });
  const [isSupabaseConnected, setIsSupabaseConnected] = useState<boolean>(false);
  const [dbState, setDbState] = useState<DbState>(() => db.getState());
  const { toasts, addToast, removeToast } = useToast();
  const [adminUser, setAdminUser] = useState<{ id: string; username: string; role: string } | null>(null);

  // Asynchronously verify JWT session token on mount
  const checkToken = async () => {
    const token = getStorageItem('admin_token');
    if (token) {
      const jwtSecret = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'default-secret-key-12345';
      const payload = await verifyJwt(token, jwtSecret);
      
      // Also support checking with the offline secret if the token is generated by fallback
      const offlinePayload = !payload ? await verifyJwt(token, 'offline-fallback-secret-999') : null;
      const validPayload = payload || offlinePayload;

      if (validPayload) {
        setIsAdminAuthenticated(true);
        setAdminUser({
          id: validPayload.id,
          username: validPayload.username,
          role: validPayload.role || 'admin'
        });
        return true;
      } else {
        // Token is tampered, expired or invalid
        setIsAdminAuthenticated(false);
        setAdminUser(null);
        removeStorageItem('admin_token');
        setView('landing');
        addToast('Sesi JWT kedaluwarsa atau tidak valid. Silakan masuk kembali.', 'error');
        return false;
      }
    } else {
      setIsAdminAuthenticated(false);
      setAdminUser(null);
      return false;
    }
  };

  useEffect(() => {
    checkToken();
  }, []);

  // Synchronize with Supabase on app mount and monitor cloud connectivity
  useEffect(() => {
    const triggerSync = async () => {
      const syncedState = await db.syncFromSupabase();
      if (syncedState) {
        setDbState(syncedState);
        setIsSupabaseConnected(true);
      } else {
        setIsSupabaseConnected(false);
      }
    };
    triggerSync();
  }, []);

  // Keep state updated from local storage
  const reloadState = () => {
    setDbState(db.getState());
  };

  // CMS HANDLERS FOR DIRECT CONTENT EDITING
  const handleSaveService = (service: Service) => {
    db.saveService(service);
    reloadState();
  };

  const handleDeleteService = (id: string) => {
    db.deleteService(id);
    reloadState();
  };

  const handleSaveBarber = (barber: Barber) => {
    db.saveBarber(barber);
    reloadState();
  };

  const handleDeleteBarber = (id: string) => {
    db.deleteBarber(id);
    reloadState();
  };

  const handleSaveAdmin = (admin: Admin) => {
    db.saveAdmin(admin);
    reloadState();
  };

  const handleDeleteAdmin = (id: string) => {
    db.deleteAdmin(id);
    reloadState();
  };

  const handleLogin = async (success: boolean) => {
    if (success) {
      await checkToken();
      setIsAdminAuthenticated(true);
      setView('dashboard');
    }
  };

  const handleLogout = () => {
    setIsAdminAuthenticated(false);
    setAdminUser(null);
    removeStorageItem('admin_token');
    setView('landing');
    addToast('Anda berhasil keluar dari sesi Admin.', 'info');
  };

  // Safe navigation
  const handleNavigate = (targetView: 'landing' | 'login' | 'dashboard') => {
    if (targetView === 'login' && isAdminAuthenticated) {
      setView('dashboard');
    } else if (targetView === 'dashboard' && !isAdminAuthenticated) {
      setView('login');
      addToast('Silakan masuk terlebih dahulu untuk mengakses dashboard.', 'info');
    } else {
      setView(targetView);
    }
  };

  // BOOKING HANDLERS
  const handleAddBooking = (newBooking: Omit<Booking, 'id' | 'createdAt' | 'status'>) => {
    db.saveBooking({
      ...newBooking,
      status: 'pending' // Initial status is pending
    });
    reloadState();
    addToast(`Terima kasih ${newBooking.customerName}, booking Anda berhasil dijadwalkan!`, 'success');
  };

  const handleUpdateStatus = (id: string, status: BookingStatus, notes?: string) => {
    db.updateBookingStatus(id, status, notes);
    reloadState();
  };

  const handleDeleteBooking = (id: string) => {
    db.deleteBooking(id);
    reloadState();
  };

  // POS TRANSACTION HANDLER
  const handleAddTransaction = (newTransaction: Omit<Transaction, 'id' | 'createdAt' | 'transactionDate' | 'transactionTime'>) => {
    db.saveTransaction(newTransaction);
    reloadState();
  };

  // DB IMPORTS/EXPORTS
  const handleImportDb = (jsonStr: string): boolean => {
    const success = db.importFromJson(jsonStr);
    if (success) {
      reloadState();
    }
    return success;
  };

  const handleExportDb = (): string => {
    return db.exportToJson();
  };

  const handleResetDb = () => {
    db.resetDatabase();
    reloadState();
  };

  return (
    <>
      <div className="flex-1 flex flex-col min-h-screen">
        {view === 'landing' && (
          <LandingPage
            onNavigate={handleNavigate}
            services={dbState.services}
            barbers={dbState.barbers}
            onBook={handleAddBooking}
          />
        )}

        {view === 'login' && (
          <AdminLogin
            onLogin={handleLogin}
            onNavigate={handleNavigate}
            addToast={addToast}
          />
        )}

        {view === 'dashboard' && (
          <AdminDashboard
            bookings={dbState.bookings}
            transactions={dbState.transactions}
            services={dbState.services}
            barbers={dbState.barbers}
            admins={dbState.admins || []}
            adminUser={adminUser || undefined}
            isSupabaseConnected={isSupabaseConnected}
            onAddBooking={handleAddBooking}
            onUpdateStatus={handleUpdateStatus}
            onDeleteBooking={handleDeleteBooking}
            onAddTransaction={handleAddTransaction}
            onImportDb={handleImportDb}
            onExportDb={handleExportDb}
            onResetDb={handleResetDb}
            onLogout={handleLogout}
            onNavigate={handleNavigate}
            addToast={addToast}
            onSaveService={handleSaveService}
            onDeleteService={handleDeleteService}
            onSaveBarber={handleSaveBarber}
            onDeleteBarber={handleDeleteBarber}
            onSaveAdmin={handleSaveAdmin}
            onDeleteAdmin={handleDeleteAdmin}
          />
        )}
      </div>

      {/* Global premium Toast Notifications */}
      <ToastContainer toasts={toasts} removeToast={removeToast} />
    </>
  );
}

export default App;
